export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'

export const ADD_PRODUCTS_TO_CART = 'ADD_PRODUCTS_TO_CART'
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART'

export const CHECKOUT = 'CHECKOUT'