export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'

export const GET_ALL_PRODUCTS_IN_CART = 'GET_ALL_PRODUCTS_IN_CART'
export const ADD_PRODUCTS_TO_CART = 'ADD_PRODUCTS_TO_CART'
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART'
export const DELETE_PRODUCT_IN_CART_ADMIN = 'DELETE_PRODUCT_IN_CART_ADMIN'

export const CHECKOUT = 'CHECKOUT'